# Generated by Django 4.2.6 on 2023-10-05 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLearningProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sampling_strategy', models.CharField(choices=[], max_length=4)),
                ('rebuild', models.IntegerField()),
                ('log_dir', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'highlighter_activelearningproject',
            },
        ),
        migrations.CreateModel(
            name='AnnotationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'highlighter_annotationproject',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('store_text', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlighter_project',
            },
        ),
        migrations.CreateModel(
            name='VocabularyAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(choices=[('l', 'local'), ('o', 'open skos')], default='l', max_length=2)),
            ],
            options={
                'db_table': 'highlighter_vocabularyapi',
            },
        ),
        migrations.CreateModel(
            name='TextHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text_type', models.CharField(choices=[('ft', 'Full Text'), ('id', 'Text ID'), ('cl', 'Text Class')], default='cl', max_length=3)),
                ('uri', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text_class', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_highlighter.project')),
            ],
            options={
                'db_table': 'highlighter_texthigh',
            },
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('txt', 'Text field'), ('frm', 'Form'), ('m', 'menu entry'), ('fn', 'Javascript function')], default='txt', max_length=4)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_highlighter.vocabularyapi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_menuEntry', to='apis_highlighter.menuentry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_highlighter.project')),
            ],
            options={
                'db_table': 'highlighter_menuentry',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('orig_string', models.CharField(blank=True, max_length=255, null=True)),
                ('text_object_id', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('del', 'deleted'), ('ap', 'approved')], max_length=4, null=True)),
                ('annotation_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_highlighter.annotationproject')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gfk_from', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_annotation', to='apis_highlighter.annotation')),
                ('text_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlighter_annotation',
            },
        ),
    ]
