# Generated by Django 2.2.11 on 2021-06-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apis_highlighter', '0003_annotationproject_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gfk_from', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
