name: Deploy to PyPi

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    #needs: test
    #if: github.repository_owner == 'your-github-name' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - uses: bjoluc/semantic-release-config-poetry@v2
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

